// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljmqmsrqlaxawjmnmshx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqbXFtc3JxbGF4YXdqbW5tc2h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NDY5NDksImV4cCI6MjA3MjAyMjk0OX0.IV5fK0o97gwaXlcSNQWSD1yFym9dctaF5vcjlfalaxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});